
spring.application.name=HospitalManagmentSystem
spring.datasource.url=jdbc:sqlserver://hms-server-demo.database.windows.net:1433;database=hms-sql-db-demo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=naveen
spring.datasource.password=MN2827@nav
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jackson.deserialization.fail-on-null-for-primitives=false
